services:

  app:
    build: .
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - ./storage:/var/www/html/storage
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306

  db:
    image: mysql:8
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: nongsan
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  dbdata: